"""
AI Reasoner

LLM-powered reasoning for generating step-by-step guidance.
Uses RAG context and screen state to produce actionable instructions.
"""

from dataclasses import dataclass
from typing import Any, Dict, List, Optional
import json
import logging

from app.ai_engine.llm_client import LLMClient, get_llm_client
from app.config import settings

logger = logging.getLogger(__name__)


@dataclass
class GuidanceStep:
    """A single guidance step generated by the reasoner."""
    step_number: int
    instruction: str
    detailed_instruction: Optional[str]
    target_element_type: Optional[str]
    target_element_label: Optional[str]
    action_type: str  # click, type, select, etc.
    action_value: Optional[str]  # Value to type/select
    keywords: List[str]  # Keywords to match in UI elements


@dataclass
class GuidanceResult:
    """Complete guidance result from the reasoner."""
    query: str
    steps: List[GuidanceStep]
    context_summary: Optional[str]
    confidence: float
    reasoning: Optional[str]


# System prompt for guidance generation
GUIDANCE_SYSTEM_PROMPT = """You are an AI assistant that generates step-by-step UI guidance for users.

Your task is to analyze a user's question and relevant documentation context to produce clear, actionable steps.

For each step, you must specify:
1. A clear instruction for the user
2. The type of UI element to interact with (button, input, link, etc.)
3. The label or text of the element to find
4. The action to perform (click, type, select, etc.)
5. Any value to enter (for type/select actions)
6. Keywords to help locate the element

Guidelines:
- Keep instructions concise and clear
- Use action verbs: Click, Type, Select, Enter, Navigate
- Be specific about element labels and types
- Break complex actions into simple steps
- Maximum 10 steps per response
- If unsure, include alternative approaches

Output Format:
You must respond with valid JSON matching this structure:
{
    "steps": [
        {
            "step_number": 1,
            "instruction": "Click the 'New Issue' button",
            "detailed_instruction": "Look for the green button labeled 'New Issue' in the top right of the page",
            "target_element_type": "button",
            "target_element_label": "New Issue",
            "action_type": "click",
            "action_value": null,
            "keywords": ["new", "issue", "create"]
        }
    ],
    "context_summary": "Based on the GitHub documentation...",
    "confidence": 0.85,
    "reasoning": "The user wants to create an issue, which requires..."
}
"""


class AIReasoner:
    """
    LLM-powered reasoning for guidance generation.

    Combines user query, RAG context, and screen state to
    generate step-by-step guidance.
    """

    def __init__(self, llm_client: Optional[LLMClient] = None):
        """
        Initialize AI Reasoner.

        Args:
            llm_client: LLM client instance (will be created if None)
        """
        self._llm_client = llm_client
        self._initialized = False

    async def _ensure_client(self) -> LLMClient:
        """Lazily initialize LLM client."""
        if self._llm_client is None:
            # Skip health check for faster initialization (client validates on first use)
            self._llm_client = await get_llm_client(skip_health_check=True)
            self._initialized = True
        return self._llm_client

    def _build_context_prompt(
        self,
        query: str,
        rag_results: Optional[List[Dict[str, Any]]] = None,
        screen_elements: Optional[List[Dict[str, Any]]] = None,
        application_context: Optional[str] = None,
    ) -> str:
        """
        Build the prompt with all available context.

        Args:
            query: User's question
            rag_results: RAG search results from knowledge base
            screen_elements: Detected UI elements from screen
            application_context: Current application name/context

        Returns:
            Complete prompt string
        """
        prompt_parts = []

        # User query
        prompt_parts.append(f"## User Question\n{query}")

        # Application context
        if application_context:
            prompt_parts.append(f"\n## Current Application\n{application_context}")

        # RAG context
        if rag_results:
            prompt_parts.append("\n## Relevant Documentation")
            for i, result in enumerate(rag_results[:settings.GUIDANCE_RAG_TOP_K], 1):
                doc_name = result.get("doc_name", "Unknown")
                text = result.get("chunk_text", result.get("text", ""))
                prompt_parts.append(f"\n### Source {i}: {doc_name}\n{text}")

        # Screen elements (if available)
        if screen_elements:
            prompt_parts.append("\n## Available UI Elements")
            # Summarize elements for context
            element_summary = []
            for elem in screen_elements[:20]:  # Limit to 20 elements
                label = elem.get("label", "")
                elem_type = elem.get("type", "unknown")
                if label:
                    element_summary.append(f"- {elem_type}: \"{label}\"")
                else:
                    element_summary.append(f"- {elem_type} (no label)")
            prompt_parts.append("\n".join(element_summary))

        # Instructions
        prompt_parts.append("\n## Instructions")
        prompt_parts.append(
            "Based on the user's question and the available context, "
            "generate step-by-step guidance. If documentation is provided, "
            "base your steps on that information. If UI elements are listed, "
            "try to reference them in your steps."
        )

        return "\n".join(prompt_parts)

    async def generate_guidance(
        self,
        query: str,
        rag_results: Optional[List[Dict[str, Any]]] = None,
        screen_elements: Optional[List[Dict[str, Any]]] = None,
        application_context: Optional[str] = None,
    ) -> GuidanceResult:
        """
        Generate step-by-step guidance for a user query.

        Args:
            query: User's question
            rag_results: RAG search results from knowledge base
            screen_elements: Detected UI elements from screen
            application_context: Current application name/context

        Returns:
            GuidanceResult with steps and metadata
        """
        client = await self._ensure_client()

        # Build prompt
        prompt = self._build_context_prompt(
            query=query,
            rag_results=rag_results,
            screen_elements=screen_elements,
            application_context=application_context,
        )

        logger.debug(f"Generating guidance for query: {query[:100]}...")

        try:
            # Generate structured response
            logger.info(f"Calling LLM for guidance generation...")
            response = await client.generate_json(
                prompt=prompt,
                system_prompt=GUIDANCE_SYSTEM_PROMPT,
            )
            logger.info(f"LLM response received, keys: {list(response.keys())}")

            # Check for error in response
            if "error" in response:
                logger.warning(f"LLM returned error: {response.get('error')}")

            # Parse steps
            steps = []
            raw_steps = response.get("steps", [])
            logger.info(f"Parsing {len(raw_steps)} steps from LLM response")

            for step_data in raw_steps:
                step = GuidanceStep(
                    step_number=step_data.get("step_number", len(steps) + 1),
                    instruction=step_data.get("instruction", ""),
                    detailed_instruction=step_data.get("detailed_instruction"),
                    target_element_type=step_data.get("target_element_type"),
                    target_element_label=step_data.get("target_element_label"),
                    action_type=step_data.get("action_type", "click"),
                    action_value=step_data.get("action_value"),
                    keywords=step_data.get("keywords", []),
                )
                steps.append(step)

            result = GuidanceResult(
                query=query,
                steps=steps,
                context_summary=response.get("context_summary"),
                confidence=response.get("confidence", 0.7),
                reasoning=response.get("reasoning"),
            )

            logger.info(
                f"Generated {len(steps)} guidance steps with "
                f"confidence {result.confidence:.2f}"
            )

            return result

        except Exception as e:
            import traceback
            logger.error(f"Failed to generate guidance: {e}")
            logger.error(f"Traceback: {traceback.format_exc()}")
            # Return empty result on error
            return GuidanceResult(
                query=query,
                steps=[],
                context_summary=None,
                confidence=0.0,
                reasoning=f"Error generating guidance: {str(e)}",
            )

    async def refine_step(
        self,
        step: GuidanceStep,
        screen_elements: List[Dict[str, Any]],
        error_message: Optional[str] = None,
    ) -> GuidanceStep:
        """
        Refine a guidance step based on actual screen state.

        Use this when a step's target element wasn't found or
        when verification failed.

        Args:
            step: Original guidance step
            screen_elements: Current screen elements
            error_message: Optional error message for context

        Returns:
            Refined guidance step
        """
        client = await self._ensure_client()

        # Build refinement prompt
        prompt = f"""## Original Step
Instruction: {step.instruction}
Target Type: {step.target_element_type}
Target Label: {step.target_element_label}
Action: {step.action_type}

## Problem
{error_message or "The target element was not found on screen."}

## Available UI Elements
"""
        for elem in screen_elements[:15]:
            label = elem.get("label", "")
            elem_type = elem.get("type", "unknown")
            prompt += f"- {elem_type}: \"{label}\"\n"

        prompt += """
## Task
Suggest an alternative approach or clarify the step.
Look at the available elements and try to find a matching one.
"""

        try:
            response = await client.generate_json(
                prompt=prompt,
                system_prompt=GUIDANCE_SYSTEM_PROMPT,
            )

            if response.get("steps"):
                refined = response["steps"][0]
                return GuidanceStep(
                    step_number=step.step_number,
                    instruction=refined.get("instruction", step.instruction),
                    detailed_instruction=refined.get("detailed_instruction"),
                    target_element_type=refined.get("target_element_type", step.target_element_type),
                    target_element_label=refined.get("target_element_label", step.target_element_label),
                    action_type=refined.get("action_type", step.action_type),
                    action_value=refined.get("action_value", step.action_value),
                    keywords=refined.get("keywords", step.keywords),
                )

        except Exception as e:
            logger.error(f"Failed to refine step: {e}")

        return step  # Return original on failure

    async def explain_step(
        self,
        step: GuidanceStep,
        rag_results: Optional[List[Dict[str, Any]]] = None,
    ) -> str:
        """
        Generate a detailed explanation for a guidance step.

        Args:
            step: Guidance step to explain
            rag_results: Related documentation for context

        Returns:
            Detailed explanation string
        """
        client = await self._ensure_client()

        prompt = f"""Explain this step in more detail:

Step: {step.instruction}
Action: {step.action_type} on {step.target_element_type} "{step.target_element_label}"
"""

        if rag_results:
            prompt += "\nRelated documentation:\n"
            for result in rag_results[:2]:
                text = result.get("chunk_text", result.get("text", ""))
                prompt += f"- {text[:200]}...\n"

        prompt += "\nProvide a clear, helpful explanation of why this step is needed and what it accomplishes."

        try:
            explanation = await client.generate(
                prompt=prompt,
                system_prompt="You are a helpful assistant explaining UI guidance steps. Be concise and clear.",
            )
            return explanation

        except Exception as e:
            logger.error(f"Failed to generate explanation: {e}")
            return step.detailed_instruction or step.instruction
